from __future__ import annotations
from pathlib import Path
from datetime import datetime
import csv
import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .parse import MemberRecord


def write_member_csv(records: list[MemberRecord], out_dir: Path) -> Path:
    """Write structured member records to CSV."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"members_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.csv"
    
    fields = [
        "rank", "name", "power", "kills", "weekly_contribution", 
        "construction", "tribe_assistance", "gold_donation", 
        "read_rank", "is_valid"
    ]
    
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction='ignore')
        w.writeheader()
        for rec in records:
            w.writerow(rec.__dict__)
            
    return path


def write_member_json(records: list[MemberRecord], out_dir: Path, filename: str = None) -> Path:
    """Write structured member records to JSON."""
    out_dir.mkdir(parents=True, exist_ok=True)
    if filename is None:
        filename = f"members_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.json"
    path = out_dir / filename
    
    data = [rec.__dict__ for rec in records]
    
    # Clean up non-serializable fields if any (dataclasses usually fine)
    # We want a clean list of dicts
    
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
            
    return path


def write_member_html(records: list[MemberRecord], out_dir: Path, filename: str = None) -> Path:
    """Write structured member records to a shareable HTML page."""
    out_dir.mkdir(parents=True, exist_ok=True)
    if filename is None:
        filename = f"members_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.html"
    path = out_dir / filename
    
    headers = [
        "Rank", "Name", "Power", "Kills", "Weekly Contrib", 
        "Construction", "Assistance", "Gold Donation"
    ]
    
    table_headers = "".join(f"<th>{h}</th>" for h in headers)
    
    rows = []
    for rec in records:
        row = f"""
        <tr>
            <td>{rec.rank or ''}</td>
            <td><strong>{escape_html(rec.name)}</strong></td>
            <td>{rec.power or 0:,}</td>
            <td>{rec.kills or 0:,}</td>
            <td>{rec.weekly_contribution or 0:,}</td>
            <td>{rec.construction or 0:,}</td>
            <td>{rec.tribe_assistance or 0:,}</td>
            <td>{rec.gold_donation or 0:,}</td>
        </tr>
        """
        rows.append(row)
    
    html = f"""<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fate War Alliance Tracking</title>
    <!-- jQuery and DataTables CSS/JS for better interactivity -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 20px; background: #f0f2f5; color: #1c1e21; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        header {{ background: #1877f2; color: white; padding: 20px; border-radius: 8px 8px 0 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        h1 {{ margin: 0; font-size: 24px; }}
        .summary {{ background: white; padding: 15px; border-bottom: 1px solid #ddd; display: flex; gap: 20px; font-size: 14px; color: #606770; }}
        .table-container {{ background: white; padding: 20px; border-radius: 0 0 8px 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); overflow-x: auto; }}
        table.dataTable {{ border-collapse: collapse !important; width: 100% !important; }}
        table.dataTable thead th {{ background-color: #f0f2f5; color: #4b4f56; border-bottom: 2px solid #ddd !important; padding: 12px; }}
        table.dataTable tbody td {{ padding: 12px; border-bottom: 1px solid #eee; }}
        .footer {{ margin-top: 20px; text-align: center; font-size: 12px; color: #90949c; }}
        
        /* Power color coding */
        .power-high {{ color: #d32f2f; font-weight: bold; }}
        .power-mid {{ color: #1976d2; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Fate War Alliance Tracking</h1>
        </header>
        <div class="summary">
            <div><strong>Total Members:</strong> {len(records)}</div>
            <div><strong>Last Updated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</div>
        </div>
        <div class="table-container">
            <table id="membersTable" class="display">
                <thead>
                    <tr>{table_headers}</tr>
                </thead>
                <tbody>
                    {"".join(rows)}
                </tbody>
            </table>
        </div>
        <div class="footer">
            Generated by FateWarScraper
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function() {{
            $('#membersTable').DataTable({{
                "pageLength": 50,
                "order": [[ 0, "asc" ]],
                "responsive": true,
                "language": {{
                    "search": "Search Member:"
                }}
            }});
        }});
    </script>
</body>
</html>
"""
    path.write_text(html, encoding="utf-8")
    return path


def write_csv(lines: list[str], out_dir: Path) -> Path:
    """Legacy raw text export."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"alliance_raw_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.csv"
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["RawText"])
        for line in lines:
            w.writerow([line])
    return path


def write_html(lines: list[str], out_dir: Path) -> Path:
    """Legacy raw text export."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"alliance_raw_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.html"
    rows = "\n".join(f"<tr><td>{escape_html(line)}</td></tr>" for line in lines)
    html = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Alliance OCR</title></head>
<body>
<table border="1">
{rows}
</table>
</body></html>
"""
    path.write_text(html, encoding="utf-8")
    return path


def escape_html(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;")
             .replace("'", "&#39;"))
